Repository CrayLabs/SmartRedis, pull requests merged in 2021-08, with the labels that each got.

#108 Fix minor typos in SmartRedis documentation
  doc/clients/fortran.rst
  doc/data_structures.rst
  include/c_client.h
  include/client.h
  include/pyclient.h
  src/fortran/client.F90
  src/python/module/smartredis/client.py
  src/python/module/smartredis/dataset.py
Labels: area: docs

#128 Add logic to create third-party directory if it doesn't exist
  build-scripts/build_test_deps.sh
Labels: area: build

#113 Refactor CPP client command structure
  CMakeLists.txt
  build-scripts/build-redisai-gpu.sh
  doc/changelog.rst
  doc/developer/testing.rst
  include/addressanycommand.h
  include/addressatcommand.h
  include/client.h
  include/clusterinfocommand.h
  include/command.h
  include/commandlist.h
  include/commandlist.tcc
  include/commandreplyparser.h
  include/compoundcommand.h
  include/dbinfocommand.h
  include/gettensorcommand.h
  include/keyedcommand.h
  include/multikeycommand.h
  include/nonkeyedcommand.h
  include/pyclient.h
  include/redis.h
  include/rediscluster.h
  include/redisserver.h
  include/singlekeycommand.h
  include/tensorbase.h
  src/cpp/addressanycommand.cpp
  src/cpp/addressatcommand.cpp
  src/cpp/client.cpp
  src/cpp/clusterinfocommand.cpp
  src/cpp/command.cpp
  src/cpp/commandlist.cpp
  src/cpp/compoundcommand.cpp
  src/cpp/dbinfocommand.cpp
  src/cpp/gettensorcommand.cpp
  src/cpp/keyedcommand.cpp
  src/cpp/multikeycommand.cpp
  src/cpp/nonkeyedcommand.cpp
  src/cpp/redis.cpp
  src/cpp/rediscluster.cpp
  src/cpp/singlekeycommand.cpp
  tests/cpp/unit-tests/CMakeLists.txt
  tests/cpp/unit-tests/test_addressanycommand.cpp
  tests/cpp/unit-tests/test_addressatcommand.cpp
  tests/cpp/unit-tests/test_client.cpp
  tests/cpp/unit-tests/test_clusterinfocommand.cpp
  tests/cpp/unit-tests/test_command.cpp
  tests/cpp/unit-tests/test_commandlist.cpp
  tests/cpp/unit-tests/test_compoundcommand.cpp
  tests/cpp/unit-tests/test_dbinfocommand.cpp
  tests/cpp/unit-tests/test_multikeycommand.cpp
  tests/cpp/unit-tests/test_singlekeycommand.cpp
  tests/cpp/unit-tests/test_ssdb.cpp
Labels: type: refactor, area: python, area: C++
