Repository CrayLabs/SmartRedis, pull requests merged in 2023-09, with the labels that each got.

#397 Update `cibuildwheel` version
  .github/workflows/build_wheels.yml
  .github/workflows/release.yml
Labels: area: CI/CD

#398 Update changelog for release
  doc/changelog.rst
Labels: area: docs

#399 Bump SR version number to 0.4.2
  CMakeLists.txt
  setup.cfg
Labels: area: docs, area: build

#396 lcov update
  .github/workflows/run_tests.yml
  Makefile
  doc/changelog.rst
Labels: area: third-party

#402 Update RedisAI version to v1.2.7
  .github/workflows/run_tests.yml
  Makefile
  doc/changelog.rst
Labels: area: third-party

#395 Add a contributing reference to SmartRedis pointing to SmartSim
  CONTRIBUTING.md
  doc/changelog.rst
Labels: area: docs

#404 Model chunking support
  doc/changelog.rst
  include/client.h
  include/command.h
  include/commandreply.h
  include/pyclient.h
  include/redis.h
  include/rediscluster.h
  include/redisserver.h
  src/cpp/client.cpp
  src/cpp/redis.cpp
  src/cpp/rediscluster.cpp
  src/cpp/redisserver.cpp
  src/python/bindings/bind.cpp
  src/python/module/smartredis/client.py
  src/python/src/pyclient.cpp
  tests/cpp/client_test_mnist.cpp
  tests/cpp/unit-tests/test_client_ensemble.cpp
  tests/python/test_errors.py
  tests/python/test_model_methods_torch.py
Labels: type: feature, area: test, area: python, area: C++
