Repository CrayLabs/SmartRedis, pull requests merged in 2023-07, with the labels that each got.

#367 Assorted documentation updates
  doc/changelog.rst
  doc/install/docker.rst
  doc/install/lib.rst
  doc/installation.rst
Labels: area: docs

#368 Release 0.4.1
  README.md
  doc/changelog.rst
  doc/testing.rst
  setup.cfg
Labels: area: docs

#364 Reuse existing Redis connection when executing CLUSTER MAP command
  doc/changelog.rst
  src/cpp/rediscluster.cpp
Labels: type: performance, area: C++, Short task

#371 mitigate lint errors, apply formatters
  .github/workflows/run_tests.yml
  .pylintrc
  Makefile
  doc/changelog.rst
  pyproject.toml
  requirements-dev.txt
  setup.cfg
  src/python/module/smartredis/__init__.py
  src/python/module/smartredis/client.py
  src/python/module/smartredis/configoptions.py
  src/python/module/smartredis/dataset.py
  src/python/module/smartredis/dataset_utils.py
  src/python/module/smartredis/error.py
  src/python/module/smartredis/logcontext.py
  src/python/module/smartredis/logger.py
  src/python/module/smartredis/srobject.py
  src/python/module/smartredis/util.py
  tests/python/test_address.py
  tests/python/test_configoptions.py
  tests/python/test_dataset_aggregation.py
  tests/python/test_dataset_methods.py
  tests/python/test_dataset_ops.py
  tests/python/test_errors.py
  tests/python/test_logging.py
  tests/python/test_nonkeyed_cmd.py
  tests/python/test_prefixing.py
  tests/python/test_put_get_tensor.py
  tests/python/test_tensor_ops.py
Labels: area: python, area: CI/CD

#379 Update language support matrix
  doc/changelog.rst
  doc/overview.rst
Labels: area: docs

#381 Make testing more robust
  Makefile
  doc/changelog.rst
Labels: area: build, area: test, area: CI/CD

#386 Static branch fixups
  .github/workflows/run_tests.yml
  CMakeLists.txt
  Makefile
  conftest.py
  doc/changelog.rst
  examples/parallel/cpp/CMakeLists.txt
  examples/parallel/cpp/smartredis_mnist.cpp
  examples/parallel/fortran/CMakeLists.txt
  examples/parallel/fortran/smartredis_mnist.F90
  examples/serial/c/CMakeLists.txt
  examples/serial/c/example_put_unpack_1D.c
  examples/serial/cpp/CMakeLists.txt
  examples/serial/cpp/smartredis_mnist.cpp
  examples/serial/cpp/smartredis_model.cpp
  examples/serial/fortran/CMakeLists.txt
  examples/test_examples.py
  smartredis_defs.cmake
  tests/c/CMakeLists.txt
  tests/c/test_c_client.py
  tests/cpp/CMakeLists.txt
  tests/cpp/test_cpp_client.py
  tests/cpp/unit-tests/CMakeLists.txt
  tests/cpp/unit-tests/test_unit_cpp_client.py
  tests/fortran/CMakeLists.txt
  tests/fortran/test_fortran_client.py
Labels: area: build, area: test, bug: major, area: CI/CD

#388 Fix Postmerge tests
  .github/workflows/run_post_merge_tests.yml
  doc/changelog.rst
Labels: bug: minor, area: CI/CD
