Repository CrayLabs/SmartRedis, pull requests merged in 2023-11, with the labels that each got.

#423 Add links to RAI and TS docs
  doc/advanced_topics.rst
  doc/changelog.rst
  doc/clients/c-plus.rst
  doc/clients/c.rst
  doc/clients/fortran.rst
  doc/clients/python.rst
  doc/conf.py
  doc/data_structures.rst
  doc/developer/testing.rst
  doc/examples/cpp_api_examples.rst
  doc/examples/python_api_examples.rst
  doc/overview.rst
  src/python/module/smartredis/client.py
Labels: area: docs

#427 Make Dataset::add_tensor() const correct
  .github/workflows/run_static_and_examples.yml
  .github/workflows/run_tests.yml
  doc/changelog.rst
  include/dataset.h
  include/tensor.h
  include/tensor.tcc
  include/tensorbase.h
  include/tensorpack.h
  src/cpp/dataset.cpp
  src/cpp/tensorbase.cpp
  src/cpp/tensorpack.cpp
Labels: User Issue, area: C++

#430 More const correctness fixes
  doc/changelog.rst
  include/client.h
  src/cpp/client.cpp
Labels: User Issue, area: C++, bug: minor
