Repository CrayLabs/SmartRedis, pull requests merged in 2024-04, with the labels that each got.

#474 Add socket time out environment variable
  doc/runtime.rst
  include/redisserver.h
  src/cpp/redis.cpp
  src/cpp/rediscluster.cpp
  src/cpp/redisserver.cpp
  tests/cpp/unit-tests/test_redisserver.cpp
Labels: area: C++, type: usability

#477 Remove unused parameter model name in _get_model_script_db()
  doc/changelog.rst
  include/rediscluster.h
  src/cpp/rediscluster.cpp
Labels: type: refactor, area: C++

#478 Enforce matching type for dataset::unpack_tensor
  doc/changelog.rst
  include/dataset.h
  src/cpp/dataset.cpp
  tests/cpp/unit-tests/test_dataset.cpp
Labels: type: refactor, area: C++

#479 Remove unused memory layout constructor parameter for TensorBase.
  doc/changelog.rst
  include/tensor.tcc
  include/tensorbase.h
  src/cpp/tensorbase.cpp
Labels: type: refactor, area: C++

#486 Auto-post release PR to develop
  .github/workflows/release.yml
  doc/changelog.rst
Labels: area: CI/CD

#488 Readthedocs changelog errors
  doc/changelog.md
Labels: area: docs, ignore-for-release

#489 Readthedocs styling error from headers
  doc/changelog.md
Labels: area: docs, ignore-for-release
